Jwy/integer step
Space-Systems/neptune pull request #35
Opened 2023-10-12 15:29 UTC by B05208038

In this part, I look into the integer limitation for the time step. The following are the changes:

1. neptune.inp
time step change to 2.5 to check if it works out. 

2. rdinp.f90 
add double precision function into the file, and make output_step double precision  

3. neptuneClass.f90
move all of the output_step function from integer catagory to double precision catagory 

I did some compiling test and it should work. (hopefully)

2023-10-13 09:38 UTC, daluar requested changes
Looking good! It's basically minor stuff

2023-10-13 09:38 UTC, daluar commented on src/neptuneClass.f90
> +        !integer                         :: output_step                          ! output time step in seconds, 5 mins as default
Now we can remove this commented code :)

2023-10-13 09:38 UTC, daluar commented on src/neptuneClass.f90
> +        real(dp)                        :: output_step                          ! output time step that can touch double precision
Keep the part of the comment related to the default value

2023-10-13 09:38 UTC, daluar commented on src/neptuneClass.f90
> +        !call this%set_input(parName=C_OUTPUT_STEP, valType='integer', initFlag=.true.)
To be removed

2023-10-13 09:38 UTC, daluar commented on src/neptuneClass.f90
> +          case(C_GEOPOTENTIAL,  C_OPT_SAT_PROPERTIES,   C_PAR_INT_COV_METHOD, & ! remove C_OUTPUT_STEP
We don't need the comment anymore

2023-10-13 09:38 UTC, daluar commented on src/neptuneClass.f90
> +          case(C_PAR_MASS, C_PAR_CROSS_SECTION, C_PAR_CDRAG, C_OUTPUT_STEP,         & ! add C_OUTPUT_STEP
We don't need the comment anymore

2023-10-13 09:38 UTC, daluar commented on src/neptuneClass.f90
> +        ! call this%set_input(parName=C_OUTPUT_STEP, valType='integer', initFlag=.true.)
Same, please remove this comment

2023-10-13 09:38 UTC, daluar commented on work/input/neptune.inp
> +  2.5
Maybe you can keep the same value, but as 60.0

2023-10-13 09:38 UTC, daluar commented on src/rdinp.f90
> +  real(dp)    :: dch_inp            ! input file channel
These three variables seem unneeded

2023-10-13 09:38 UTC, daluar commented on src/rdinp.f90
> +  derr =  neptune%setNeptuneVar("OUTPUT_STEP", ctemp)
This one should still be `ierr`

2023-10-13 19:00 UTC, B05208038 commented
All of them should be fixed atm. (hopefully)

2025-01-10 14:48 UTC, zurdala commented
Closed in favor of #36

2025-01-10 14:48 UTC, closed without merging